Repository IT24102532/parkingManagement, pull requests merged in 2025-03, with the labels that each got.

#19 Fixed Issue 1: Handled File Read and Write effectively
  src/main/java/lk/sliit/parkingmanagement/oopapp/config/FileConfig.java
  src/main/java/lk/sliit/parkingmanagement/oopapp/servlets/HelloServlet.java
  src/main/resources/config.properties
  src/main/webapp/WEB-INF/data/bookings.json
  src/main/webapp/WEB-INF/data/parkingSlots.json
  src/main/webapp/WEB-INF/data/transactions.json
  src/main/webapp/WEB-INF/data/users.json
Labels: fix

#23 initialize booking stylesheet
  dilnaka.md
  src/main/webapp/css/booking.css
  src/main/webapp/scss/booking.scss
Labels: enhancement

#24 completed the booking page styling part
  src/main/java/lk/sliit/parkingmanagement/oopapp/servlets/BookingServlet.java
  src/main/webapp/booking.jsp
  src/main/webapp/css/booking.css
Labels: enhancement

#26 Member/kavindu
  src/main/webapp/admin-dashboard.jsp
  src/main/webapp/css/booking.css
  src/main/webapp/css/dashboard.css
  src/main/webapp/css/dual_container_global.css
  src/main/webapp/scss/dashboard.scss
Labels: enhancement

#29 Member/kavindu
  src/main/java/lk/sliit/parkingmanagement/oopapp/JsonHelper.java
  src/main/java/lk/sliit/parkingmanagement/oopapp/ParkingSlot.java
  src/main/java/lk/sliit/parkingmanagement/oopapp/servlets/BookSlotServlet.java
  src/main/java/lk/sliit/parkingmanagement/oopapp/servlets/CheckAvailabilityServlet.java
  src/main/java/lk/sliit/parkingmanagement/oopapp/servlets/FindAvailableLocationsServlet.java
  src/main/java/lk/sliit/parkingmanagement/oopapp/servlets/HelloServlet.java
  src/main/java/lk/sliit/parkingmanagement/oopapp/servlets/TestServlet.java
  src/main/webapp/booking.jsp
  src/main/webapp/css/booking.css
  src/main/webapp/js/search_ajax.js
  src/main/webapp/scss/booking.scss
  src/main/webapp/testing.jsp
Labels: enhancement, fix

#35 Hot fix
  src/main/webapp/admin-users.jsp
  src/main/webapp/checkout.jsp
  src/main/webapp/css/checkout.css
  src/main/webapp/css/users.css
Labels: fix
